In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
print(a)

[ 0.10749024  0.0945113   0.4504607   1.70879641 -0.32777465]


In [3]:
print(a.shape)

(5,)


In [4]:
print(np.dot(a,a.T))

3.250822769245281


In [5]:
a = np.random.randn(5,1)
print(a)

[[ 1.89320692]
 [-0.27117778]
 [-0.52791914]
 [-0.13899475]
 [-0.75773232]]


In [6]:
print(a.T)

[[ 1.89320692 -0.27117778 -0.52791914 -0.13899475 -0.75773232]]


For Neural Networks, do not use "rank 1(n) array" (cell 2), instead use (n,1) shape (cell 5).

In [7]:
a = np.random.randn(5)

In [8]:
assert(a.shape == (5,1))

AssertionError: 

In [ ]:
a = np.random.randn(5,1)
assert(a.shape == (5,1))

Takeaways are to simplify your code, don't use rank 1 arrays. Always use either n by one matrices, basically column vector, or one by n matrices, row vectors. Feel free to insert a lot of insertion statements, so double-check the dimensions of the matrices or vectors.